name: Code review
on:
  - push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
        fetch-depth: 0
    - run: |
        git fetch --no-tags --prune origin
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - uses: adwerx/pronto-ruby@v2.8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RUBOCOP_CONFIG: ./pronto/rubocop/rubocop.yml
        YAMLLINT_OPTS: -c ./pronto/yamllint/yamllint.yml
        POPER_CHARACTER_LIMIT_NUMBER: 120
        POPER_SUMMARY_CHARACTER_LIMIT_NUMBER: 90
      with:
        runners: >-
          brakeman fasterer poper rails_best_practices rails_schema reek rubocop scss yamllint
