name: Run tests

on:
  - push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    env:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      RAILS_ENV: test
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
          fetch-depth: 0
      - run: |
          git fetch --no-tags --prune origin
      - name: Build images
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml build app
      - name: Setup database
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml run app rake db:setup
      - name: Run tests
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml run app rspec spec
